/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123Char125DotmdRouteImport } from './routes/{$}[.]md'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiSearchDotjsonRouteImport } from './routes/api/search[.]json'

const Char123Char125DotmdRoute = Char123Char125DotmdRouteImport.update({
  id: '/{$}.md',
  path: '/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchDotjsonRoute = ApiSearchDotjsonRouteImport.update({
  id: '/api/search.json',
  path: '/api/search.json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/api/search.json': typeof ApiSearchDotjsonRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/api/search.json': typeof ApiSearchDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/api/search.json': typeof ApiSearchDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/{$}.md'
    | '/api/search.json'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/llms-full.txt' | '/llms.txt' | '/{$}.md' | '/api/search.json'
  id:
    | '__root__'
    | '/$'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/{$}.md'
    | '/api/search.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  Char123Char125DotmdRoute: typeof Char123Char125DotmdRoute
  ApiSearchDotjsonRoute: typeof ApiSearchDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{$}.md': {
      id: '/{$}.md'
      path: '/{$}.md'
      fullPath: '/{$}.md'
      preLoaderRoute: typeof Char123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search.json': {
      id: '/api/search.json'
      path: '/api/search.json'
      fullPath: '/api/search.json'
      preLoaderRoute: typeof ApiSearchDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  Char123Char125DotmdRoute: Char123Char125DotmdRoute,
  ApiSearchDotjsonRoute: ApiSearchDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
