/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard/onboarding'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthAcceptInvitationIdRouteImport } from './routes/_auth/accept-invitation.$id'
import { Route as DashboardOrgsOrgIdRouteRouteImport } from './routes/dashboard/orgs/$orgId/route'
import { Route as DashboardOrgsOrgIdIndexRouteImport } from './routes/dashboard/orgs/$orgId/index'
import { Route as DashboardOrgsOrgIdSettingsIndexRouteImport } from './routes/dashboard/orgs/$orgId/settings/index'
import { Route as DashboardOrgsOrgIdViewsListRouteImport } from './routes/dashboard/orgs/$orgId/views/list'
import { Route as DashboardOrgsOrgIdViewsGalleryRouteImport } from './routes/dashboard/orgs/$orgId/views/gallery'
import { Route as DashboardOrgsOrgIdViewsFoldersRouteImport } from './routes/dashboard/orgs/$orgId/views/folders'
import { Route as DashboardOrgsOrgIdSettingsTagsRouteImport } from './routes/dashboard/orgs/$orgId/settings/tags'
import { Route as DashboardOrgsOrgIdSettingsStoragePathsRouteImport } from './routes/dashboard/orgs/$orgId/settings/storage-paths'
import { Route as DashboardOrgsOrgIdSettingsStorageRouteImport } from './routes/dashboard/orgs/$orgId/settings/storage'
import { Route as DashboardOrgsOrgIdSettingsRegistrationRouteImport } from './routes/dashboard/orgs/$orgId/settings/registration'
import { Route as DashboardOrgsOrgIdSettingsOcrRouteImport } from './routes/dashboard/orgs/$orgId/settings/ocr'
import { Route as DashboardOrgsOrgIdSettingsMigrationRouteImport } from './routes/dashboard/orgs/$orgId/settings/migration'
import { Route as DashboardOrgsOrgIdSettingsMembersRouteImport } from './routes/dashboard/orgs/$orgId/settings/members'
import { Route as DashboardOrgsOrgIdSettingsGeneralRouteImport } from './routes/dashboard/orgs/$orgId/settings/general'
import { Route as DashboardOrgsOrgIdSettingsDocumentTypesRouteImport } from './routes/dashboard/orgs/$orgId/settings/document-types'
import { Route as DashboardOrgsOrgIdSettingsCustomPropertiesRouteImport } from './routes/dashboard/orgs/$orgId/settings/custom-properties'
import { Route as DashboardOrgsOrgIdDocumentsIdRouteImport } from './routes/dashboard/orgs/$orgId/documents.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInvitationIdRoute = AuthAcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardOrgsOrgIdRouteRoute = DashboardOrgsOrgIdRouteRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrgsOrgIdIndexRoute = DashboardOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
} as any)
const DashboardOrgsOrgIdSettingsIndexRoute =
  DashboardOrgsOrgIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdViewsListRoute =
  DashboardOrgsOrgIdViewsListRouteImport.update({
    id: '/views/list',
    path: '/views/list',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdViewsGalleryRoute =
  DashboardOrgsOrgIdViewsGalleryRouteImport.update({
    id: '/views/gallery',
    path: '/views/gallery',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdViewsFoldersRoute =
  DashboardOrgsOrgIdViewsFoldersRouteImport.update({
    id: '/views/folders',
    path: '/views/folders',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsTagsRoute =
  DashboardOrgsOrgIdSettingsTagsRouteImport.update({
    id: '/settings/tags',
    path: '/settings/tags',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsStoragePathsRoute =
  DashboardOrgsOrgIdSettingsStoragePathsRouteImport.update({
    id: '/settings/storage-paths',
    path: '/settings/storage-paths',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsStorageRoute =
  DashboardOrgsOrgIdSettingsStorageRouteImport.update({
    id: '/settings/storage',
    path: '/settings/storage',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsRegistrationRoute =
  DashboardOrgsOrgIdSettingsRegistrationRouteImport.update({
    id: '/settings/registration',
    path: '/settings/registration',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsOcrRoute =
  DashboardOrgsOrgIdSettingsOcrRouteImport.update({
    id: '/settings/ocr',
    path: '/settings/ocr',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsMigrationRoute =
  DashboardOrgsOrgIdSettingsMigrationRouteImport.update({
    id: '/settings/migration',
    path: '/settings/migration',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsMembersRoute =
  DashboardOrgsOrgIdSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsGeneralRoute =
  DashboardOrgsOrgIdSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsDocumentTypesRoute =
  DashboardOrgsOrgIdSettingsDocumentTypesRouteImport.update({
    id: '/settings/document-types',
    path: '/settings/document-types',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdSettingsCustomPropertiesRoute =
  DashboardOrgsOrgIdSettingsCustomPropertiesRouteImport.update({
    id: '/settings/custom-properties',
    path: '/settings/custom-properties',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)
const DashboardOrgsOrgIdDocumentsIdRoute =
  DashboardOrgsOrgIdDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => DashboardOrgsOrgIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdRouteRouteWithChildren
  '/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/dashboard/orgs/$orgId/': typeof DashboardOrgsOrgIdIndexRoute
  '/dashboard/orgs/$orgId/documents/$id': typeof DashboardOrgsOrgIdDocumentsIdRoute
  '/dashboard/orgs/$orgId/settings/custom-properties': typeof DashboardOrgsOrgIdSettingsCustomPropertiesRoute
  '/dashboard/orgs/$orgId/settings/document-types': typeof DashboardOrgsOrgIdSettingsDocumentTypesRoute
  '/dashboard/orgs/$orgId/settings/general': typeof DashboardOrgsOrgIdSettingsGeneralRoute
  '/dashboard/orgs/$orgId/settings/members': typeof DashboardOrgsOrgIdSettingsMembersRoute
  '/dashboard/orgs/$orgId/settings/migration': typeof DashboardOrgsOrgIdSettingsMigrationRoute
  '/dashboard/orgs/$orgId/settings/ocr': typeof DashboardOrgsOrgIdSettingsOcrRoute
  '/dashboard/orgs/$orgId/settings/registration': typeof DashboardOrgsOrgIdSettingsRegistrationRoute
  '/dashboard/orgs/$orgId/settings/storage': typeof DashboardOrgsOrgIdSettingsStorageRoute
  '/dashboard/orgs/$orgId/settings/storage-paths': typeof DashboardOrgsOrgIdSettingsStoragePathsRoute
  '/dashboard/orgs/$orgId/settings/tags': typeof DashboardOrgsOrgIdSettingsTagsRoute
  '/dashboard/orgs/$orgId/views/folders': typeof DashboardOrgsOrgIdViewsFoldersRoute
  '/dashboard/orgs/$orgId/views/gallery': typeof DashboardOrgsOrgIdViewsGalleryRoute
  '/dashboard/orgs/$orgId/views/list': typeof DashboardOrgsOrgIdViewsListRoute
  '/dashboard/orgs/$orgId/settings/': typeof DashboardOrgsOrgIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdIndexRoute
  '/dashboard/orgs/$orgId/documents/$id': typeof DashboardOrgsOrgIdDocumentsIdRoute
  '/dashboard/orgs/$orgId/settings/custom-properties': typeof DashboardOrgsOrgIdSettingsCustomPropertiesRoute
  '/dashboard/orgs/$orgId/settings/document-types': typeof DashboardOrgsOrgIdSettingsDocumentTypesRoute
  '/dashboard/orgs/$orgId/settings/general': typeof DashboardOrgsOrgIdSettingsGeneralRoute
  '/dashboard/orgs/$orgId/settings/members': typeof DashboardOrgsOrgIdSettingsMembersRoute
  '/dashboard/orgs/$orgId/settings/migration': typeof DashboardOrgsOrgIdSettingsMigrationRoute
  '/dashboard/orgs/$orgId/settings/ocr': typeof DashboardOrgsOrgIdSettingsOcrRoute
  '/dashboard/orgs/$orgId/settings/registration': typeof DashboardOrgsOrgIdSettingsRegistrationRoute
  '/dashboard/orgs/$orgId/settings/storage': typeof DashboardOrgsOrgIdSettingsStorageRoute
  '/dashboard/orgs/$orgId/settings/storage-paths': typeof DashboardOrgsOrgIdSettingsStoragePathsRoute
  '/dashboard/orgs/$orgId/settings/tags': typeof DashboardOrgsOrgIdSettingsTagsRoute
  '/dashboard/orgs/$orgId/views/folders': typeof DashboardOrgsOrgIdViewsFoldersRoute
  '/dashboard/orgs/$orgId/views/gallery': typeof DashboardOrgsOrgIdViewsGalleryRoute
  '/dashboard/orgs/$orgId/views/list': typeof DashboardOrgsOrgIdViewsListRoute
  '/dashboard/orgs/$orgId/settings': typeof DashboardOrgsOrgIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdRouteRouteWithChildren
  '/_auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/dashboard/orgs/$orgId/': typeof DashboardOrgsOrgIdIndexRoute
  '/dashboard/orgs/$orgId/documents/$id': typeof DashboardOrgsOrgIdDocumentsIdRoute
  '/dashboard/orgs/$orgId/settings/custom-properties': typeof DashboardOrgsOrgIdSettingsCustomPropertiesRoute
  '/dashboard/orgs/$orgId/settings/document-types': typeof DashboardOrgsOrgIdSettingsDocumentTypesRoute
  '/dashboard/orgs/$orgId/settings/general': typeof DashboardOrgsOrgIdSettingsGeneralRoute
  '/dashboard/orgs/$orgId/settings/members': typeof DashboardOrgsOrgIdSettingsMembersRoute
  '/dashboard/orgs/$orgId/settings/migration': typeof DashboardOrgsOrgIdSettingsMigrationRoute
  '/dashboard/orgs/$orgId/settings/ocr': typeof DashboardOrgsOrgIdSettingsOcrRoute
  '/dashboard/orgs/$orgId/settings/registration': typeof DashboardOrgsOrgIdSettingsRegistrationRoute
  '/dashboard/orgs/$orgId/settings/storage': typeof DashboardOrgsOrgIdSettingsStorageRoute
  '/dashboard/orgs/$orgId/settings/storage-paths': typeof DashboardOrgsOrgIdSettingsStoragePathsRoute
  '/dashboard/orgs/$orgId/settings/tags': typeof DashboardOrgsOrgIdSettingsTagsRoute
  '/dashboard/orgs/$orgId/views/folders': typeof DashboardOrgsOrgIdViewsFoldersRoute
  '/dashboard/orgs/$orgId/views/gallery': typeof DashboardOrgsOrgIdViewsGalleryRoute
  '/dashboard/orgs/$orgId/views/list': typeof DashboardOrgsOrgIdViewsListRoute
  '/dashboard/orgs/$orgId/settings/': typeof DashboardOrgsOrgIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/onboarding'
    | '/dashboard/'
    | '/dashboard/orgs/$orgId'
    | '/accept-invitation/$id'
    | '/dashboard/orgs/$orgId/'
    | '/dashboard/orgs/$orgId/documents/$id'
    | '/dashboard/orgs/$orgId/settings/custom-properties'
    | '/dashboard/orgs/$orgId/settings/document-types'
    | '/dashboard/orgs/$orgId/settings/general'
    | '/dashboard/orgs/$orgId/settings/members'
    | '/dashboard/orgs/$orgId/settings/migration'
    | '/dashboard/orgs/$orgId/settings/ocr'
    | '/dashboard/orgs/$orgId/settings/registration'
    | '/dashboard/orgs/$orgId/settings/storage'
    | '/dashboard/orgs/$orgId/settings/storage-paths'
    | '/dashboard/orgs/$orgId/settings/tags'
    | '/dashboard/orgs/$orgId/views/folders'
    | '/dashboard/orgs/$orgId/views/gallery'
    | '/dashboard/orgs/$orgId/views/list'
    | '/dashboard/orgs/$orgId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/onboarding'
    | '/dashboard'
    | '/accept-invitation/$id'
    | '/dashboard/orgs/$orgId'
    | '/dashboard/orgs/$orgId/documents/$id'
    | '/dashboard/orgs/$orgId/settings/custom-properties'
    | '/dashboard/orgs/$orgId/settings/document-types'
    | '/dashboard/orgs/$orgId/settings/general'
    | '/dashboard/orgs/$orgId/settings/members'
    | '/dashboard/orgs/$orgId/settings/migration'
    | '/dashboard/orgs/$orgId/settings/ocr'
    | '/dashboard/orgs/$orgId/settings/registration'
    | '/dashboard/orgs/$orgId/settings/storage'
    | '/dashboard/orgs/$orgId/settings/storage-paths'
    | '/dashboard/orgs/$orgId/settings/tags'
    | '/dashboard/orgs/$orgId/views/folders'
    | '/dashboard/orgs/$orgId/views/gallery'
    | '/dashboard/orgs/$orgId/views/list'
    | '/dashboard/orgs/$orgId/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/_auth'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/dashboard/onboarding'
    | '/dashboard/'
    | '/dashboard/orgs/$orgId'
    | '/_auth/accept-invitation/$id'
    | '/dashboard/orgs/$orgId/'
    | '/dashboard/orgs/$orgId/documents/$id'
    | '/dashboard/orgs/$orgId/settings/custom-properties'
    | '/dashboard/orgs/$orgId/settings/document-types'
    | '/dashboard/orgs/$orgId/settings/general'
    | '/dashboard/orgs/$orgId/settings/members'
    | '/dashboard/orgs/$orgId/settings/migration'
    | '/dashboard/orgs/$orgId/settings/ocr'
    | '/dashboard/orgs/$orgId/settings/registration'
    | '/dashboard/orgs/$orgId/settings/storage'
    | '/dashboard/orgs/$orgId/settings/storage-paths'
    | '/dashboard/orgs/$orgId/settings/tags'
    | '/dashboard/orgs/$orgId/views/folders'
    | '/dashboard/orgs/$orgId/views/gallery'
    | '/dashboard/orgs/$orgId/views/list'
    | '/dashboard/orgs/$orgId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accept-invitation/$id': {
      id: '/_auth/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AuthAcceptInvitationIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/orgs/$orgId': {
      id: '/dashboard/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/dashboard/orgs/$orgId'
      preLoaderRoute: typeof DashboardOrgsOrgIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orgs/$orgId/': {
      id: '/dashboard/orgs/$orgId/'
      path: '/'
      fullPath: '/dashboard/orgs/$orgId/'
      preLoaderRoute: typeof DashboardOrgsOrgIdIndexRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/': {
      id: '/dashboard/orgs/$orgId/settings/'
      path: '/settings'
      fullPath: '/dashboard/orgs/$orgId/settings/'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsIndexRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/views/list': {
      id: '/dashboard/orgs/$orgId/views/list'
      path: '/views/list'
      fullPath: '/dashboard/orgs/$orgId/views/list'
      preLoaderRoute: typeof DashboardOrgsOrgIdViewsListRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/views/gallery': {
      id: '/dashboard/orgs/$orgId/views/gallery'
      path: '/views/gallery'
      fullPath: '/dashboard/orgs/$orgId/views/gallery'
      preLoaderRoute: typeof DashboardOrgsOrgIdViewsGalleryRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/views/folders': {
      id: '/dashboard/orgs/$orgId/views/folders'
      path: '/views/folders'
      fullPath: '/dashboard/orgs/$orgId/views/folders'
      preLoaderRoute: typeof DashboardOrgsOrgIdViewsFoldersRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/tags': {
      id: '/dashboard/orgs/$orgId/settings/tags'
      path: '/settings/tags'
      fullPath: '/dashboard/orgs/$orgId/settings/tags'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsTagsRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/storage-paths': {
      id: '/dashboard/orgs/$orgId/settings/storage-paths'
      path: '/settings/storage-paths'
      fullPath: '/dashboard/orgs/$orgId/settings/storage-paths'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsStoragePathsRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/storage': {
      id: '/dashboard/orgs/$orgId/settings/storage'
      path: '/settings/storage'
      fullPath: '/dashboard/orgs/$orgId/settings/storage'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsStorageRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/registration': {
      id: '/dashboard/orgs/$orgId/settings/registration'
      path: '/settings/registration'
      fullPath: '/dashboard/orgs/$orgId/settings/registration'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsRegistrationRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/ocr': {
      id: '/dashboard/orgs/$orgId/settings/ocr'
      path: '/settings/ocr'
      fullPath: '/dashboard/orgs/$orgId/settings/ocr'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsOcrRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/migration': {
      id: '/dashboard/orgs/$orgId/settings/migration'
      path: '/settings/migration'
      fullPath: '/dashboard/orgs/$orgId/settings/migration'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsMigrationRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/members': {
      id: '/dashboard/orgs/$orgId/settings/members'
      path: '/settings/members'
      fullPath: '/dashboard/orgs/$orgId/settings/members'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsMembersRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/general': {
      id: '/dashboard/orgs/$orgId/settings/general'
      path: '/settings/general'
      fullPath: '/dashboard/orgs/$orgId/settings/general'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsGeneralRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/document-types': {
      id: '/dashboard/orgs/$orgId/settings/document-types'
      path: '/settings/document-types'
      fullPath: '/dashboard/orgs/$orgId/settings/document-types'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsDocumentTypesRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/settings/custom-properties': {
      id: '/dashboard/orgs/$orgId/settings/custom-properties'
      path: '/settings/custom-properties'
      fullPath: '/dashboard/orgs/$orgId/settings/custom-properties'
      preLoaderRoute: typeof DashboardOrgsOrgIdSettingsCustomPropertiesRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
    '/dashboard/orgs/$orgId/documents/$id': {
      id: '/dashboard/orgs/$orgId/documents/$id'
      path: '/documents/$id'
      fullPath: '/dashboard/orgs/$orgId/documents/$id'
      preLoaderRoute: typeof DashboardOrgsOrgIdDocumentsIdRouteImport
      parentRoute: typeof DashboardOrgsOrgIdRouteRoute
    }
  }
}

interface DashboardOrgsOrgIdRouteRouteChildren {
  DashboardOrgsOrgIdIndexRoute: typeof DashboardOrgsOrgIdIndexRoute
  DashboardOrgsOrgIdDocumentsIdRoute: typeof DashboardOrgsOrgIdDocumentsIdRoute
  DashboardOrgsOrgIdSettingsCustomPropertiesRoute: typeof DashboardOrgsOrgIdSettingsCustomPropertiesRoute
  DashboardOrgsOrgIdSettingsDocumentTypesRoute: typeof DashboardOrgsOrgIdSettingsDocumentTypesRoute
  DashboardOrgsOrgIdSettingsGeneralRoute: typeof DashboardOrgsOrgIdSettingsGeneralRoute
  DashboardOrgsOrgIdSettingsMembersRoute: typeof DashboardOrgsOrgIdSettingsMembersRoute
  DashboardOrgsOrgIdSettingsMigrationRoute: typeof DashboardOrgsOrgIdSettingsMigrationRoute
  DashboardOrgsOrgIdSettingsOcrRoute: typeof DashboardOrgsOrgIdSettingsOcrRoute
  DashboardOrgsOrgIdSettingsRegistrationRoute: typeof DashboardOrgsOrgIdSettingsRegistrationRoute
  DashboardOrgsOrgIdSettingsStorageRoute: typeof DashboardOrgsOrgIdSettingsStorageRoute
  DashboardOrgsOrgIdSettingsStoragePathsRoute: typeof DashboardOrgsOrgIdSettingsStoragePathsRoute
  DashboardOrgsOrgIdSettingsTagsRoute: typeof DashboardOrgsOrgIdSettingsTagsRoute
  DashboardOrgsOrgIdViewsFoldersRoute: typeof DashboardOrgsOrgIdViewsFoldersRoute
  DashboardOrgsOrgIdViewsGalleryRoute: typeof DashboardOrgsOrgIdViewsGalleryRoute
  DashboardOrgsOrgIdViewsListRoute: typeof DashboardOrgsOrgIdViewsListRoute
  DashboardOrgsOrgIdSettingsIndexRoute: typeof DashboardOrgsOrgIdSettingsIndexRoute
}

const DashboardOrgsOrgIdRouteRouteChildren: DashboardOrgsOrgIdRouteRouteChildren =
  {
    DashboardOrgsOrgIdIndexRoute: DashboardOrgsOrgIdIndexRoute,
    DashboardOrgsOrgIdDocumentsIdRoute: DashboardOrgsOrgIdDocumentsIdRoute,
    DashboardOrgsOrgIdSettingsCustomPropertiesRoute:
      DashboardOrgsOrgIdSettingsCustomPropertiesRoute,
    DashboardOrgsOrgIdSettingsDocumentTypesRoute:
      DashboardOrgsOrgIdSettingsDocumentTypesRoute,
    DashboardOrgsOrgIdSettingsGeneralRoute:
      DashboardOrgsOrgIdSettingsGeneralRoute,
    DashboardOrgsOrgIdSettingsMembersRoute:
      DashboardOrgsOrgIdSettingsMembersRoute,
    DashboardOrgsOrgIdSettingsMigrationRoute:
      DashboardOrgsOrgIdSettingsMigrationRoute,
    DashboardOrgsOrgIdSettingsOcrRoute: DashboardOrgsOrgIdSettingsOcrRoute,
    DashboardOrgsOrgIdSettingsRegistrationRoute:
      DashboardOrgsOrgIdSettingsRegistrationRoute,
    DashboardOrgsOrgIdSettingsStorageRoute:
      DashboardOrgsOrgIdSettingsStorageRoute,
    DashboardOrgsOrgIdSettingsStoragePathsRoute:
      DashboardOrgsOrgIdSettingsStoragePathsRoute,
    DashboardOrgsOrgIdSettingsTagsRoute: DashboardOrgsOrgIdSettingsTagsRoute,
    DashboardOrgsOrgIdViewsFoldersRoute: DashboardOrgsOrgIdViewsFoldersRoute,
    DashboardOrgsOrgIdViewsGalleryRoute: DashboardOrgsOrgIdViewsGalleryRoute,
    DashboardOrgsOrgIdViewsListRoute: DashboardOrgsOrgIdViewsListRoute,
    DashboardOrgsOrgIdSettingsIndexRoute: DashboardOrgsOrgIdSettingsIndexRoute,
  }

const DashboardOrgsOrgIdRouteRouteWithChildren =
  DashboardOrgsOrgIdRouteRoute._addFileChildren(
    DashboardOrgsOrgIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrgsOrgIdRouteRoute: typeof DashboardOrgsOrgIdRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrgsOrgIdRouteRoute: DashboardOrgsOrgIdRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthAcceptInvitationIdRoute: typeof AuthAcceptInvitationIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthAcceptInvitationIdRoute: AuthAcceptInvitationIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
