services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: omnipaper
      POSTGRES_PASSWORD: omnipaper
      POSTGRES_DB: omnipaper
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: omnipaper:local
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://omnipaper:omnipaper@postgres:5432/omnipaper
      AUTH_SECRET: ofTnumKn9YkBNggfk2HkdJEGm4ERaKJvt8iywYP6oBE=
      ENCRYPTION_KEY: ofTnumKn9YkBNggfk2HkdJEGm4ERaKJvt8iywYP6oBE=

volumes:
  postgres-data:
